### ISSUE TITLE
!game issue

### ISSUE THREAD

**Issue by Nit-Bot-2022** [Walle-glitch/NIT-2.0#11]
bot is not listening on @bot.event On_mess...

**Comment by Walle-glitch** [comment]
Issue is fixed. 

## Key Features:

### Game State Tracking:
- `game_task`, `game_initiator`, `current_question`, `correct_answer`, and `current_game_type` track the current state of the game.
- `game_active` is a flag that indicates whether a game is running.

### Game Modes:
- The game supports two modes:
  - **Subnet**: Asks subnetting-related questions like network address, broadcast address, and number of hosts.
  - **Network Questions**: Loads and asks network-related multiple-choice questions from a JSON file.

### Continuous Gameplay:
- Once the game starts, it continues to ask questions after each answer until:
  - The user manually stops the game with `!game_stop`.
  - A 5-minute timeout occurs due to inactivity.

### Timeout Handling:
- A timeout of 300 seconds (5 minutes) is used to stop the game if no input is provided. The timeout is refreshed after each question.

### Answer Processing:
- **Subnet questions** require the user to provide the exact answer (e.g., a network address).
- **Network questions** are multiple-choice, where the user selects the correct option by entering the option number.

### Logging:
- A logger tracks events such as loading questions, generating new questions, and processing user responses. This is useful for debugging and monitoring game activity.

---

## Code Overview:

### Game State Variables:
```python
game_task = None
game_initiator = None     # The user who initiated the game
current_question = None
correct_answer = None
current_game_type = None  # The type of game (subnet/network)
game_active = False       # True if a game is active
